name: Content Addicts API

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          distribution: "mariadb"
          mysql-version: "10.11"
          root-password: ${{ secrets.MARIADB_ROOT_PASSWORD }}
          my-cnf: |
            port=${{ vars.MARIADB_HOST_PORT }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        env:
          CONTENTADDICTS_IntegrationTestsConnectionString: ${{ secrets.IntegrationTestsConnectionString }}
          CONTENTADDICTS_UnitTestsConnectionString: ${{ secrets.UnitTestsConnectionString }}
