name: Content Addicts API

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
          TZ: Europe/Budapest
        options: >-
          --health-cmd "/usr/local/bin/healthcheck.sh --connect --innodb_initialized"
          --health-start-period 15s
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
        ports:
          - ${{ vars.MARIADB_HOST_PORT }}:3306

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        env:
          CONTENTADDICTS_IntegrationTestsConnectionString: ${{ secrets.IntegrationTestsConnectionString }}
          CONTENTADDICTS_UnitTestsConnectionString: ${{ secrets.UnitTestsConnectionString }}
